### ISSUE TITLE
Shipping rate tier configuration missing in project settings and shipping rates

### ISSUE THREAD

**Issue by jberghoef** [labd/terraform-provider-commercetools#137]
Apart from the regular price and "free above" configuration for shipping rates, Commercetools also supports price tiers for shipping rates. The corresponding setting's documentation can be found here:

- https://docs.commercetools.com/api/projects/project#shippingrateinputtype
- https://docs.commercetools.com/api/projects/shippingMethods#shippingratepricetier

As can be seen here, the terraform provider currently doesn't support this option: https://github.com/labd/terraform-provider-commercetools/blob/master/commercetools/resource_shipping_zone_rate.go

It is available in the Go SDK, as can be seen here: https://github.com/labd/commercetools-go-sdk/blob/d6aa31fce767fa43c696e85b158d0bbe4426c127/commercetools/types_shipping_method.go#L12

**Comment by vitali-ausianik** [comment]
Hello Guys! What it the status of this work? Do you have some ETA to push it to release?

**Comment by qdegraaf** [comment]
Hey @vitali-ausianik ,

Thanks for your interest and the message. I'd made a first set-up over here at: https://github.com/labd/terraform-provider-commercetools/pull/142 

It's a while ago though, so I am unsure what the state of it is from a quick glance. I just ran the acceptance tests and it looks like there's still some issues with them. I am unsure when I can find time to finish the PR. If you like you're welcome to copy the branch and fix the tests, otherwise I'll let you know when I find the time to complete it.
