### ISSUE TITLE
Removal of commercetools_subscription.changes is not picked up

### ISSUE THREAD

**Issue by mvantellingen** [labd/terraform-provider-commercetools#138]
Results in a `Request body does not contain valid JSON.` error

**Comment by qdegraaf** [comment]
`Optional: True` flag does not seem to work:

```
2020-12-21T22:32:38.844+0100 [DEBUG] plugin.terraform-provider-commercetools_v0.23.0: {"statusCode":400,"message":"Request body does not contain valid JSON.","errors":[{"code":"InvalidJsonInput","message":"Request body does not contain valid JSON.","detailedErrorMessage":"actions -> changes: Missing required value"}]}
10:35
```

This does not only apply to changes, but e.g. messages as well:
```
2020-12-21T22:34:56.851+0100 [DEBUG] plugin.terraform-provider-commercetools_v0.23.0: {"statusCode":400,"message":"Request body does not contain valid JSON.","errors":[{"code":"InvalidJsonInput","message":"Request body does not contain valid JSON.","detailedErrorMessage":"actions -> messages: Missing required value"}]}
```

**Comment by qdegraaf** [comment]
Alright so this is a tricky one. Problem seems to be caused by how Go's JSON Marsalling handles empty slices.

When removing `changes` or `messages` the `SubscriptionSetChangesAction` (and the messages one) which is defined by:
```
type SubscriptionSetChangesAction struct {
	Changes []ChangeSubscription `json:"changes,omitempty"`
}
```
Returns nil due to its `omitempty` so when setting the updateAction we get 
```
"actions": [{
	"action": "setChanges"
    }]
```
Whereas we would want to get:

```
"actions": [{
	"action": "setChanges"
	"changes": []
    }]
```

We can fix this by adapting the `commercetools-sdk` to work with pointers whenever it encounters an optional argument whose value is a list. But this would involve a decent amount of refactoring.

As a sidenote another thing that could have caused a similar problem can be found in the docs [https://docs.commercetools.com/api/projects/subscriptions#update-actions](https://docs.commercetools.com/api/projects/subscriptions#update-actions). The provider should enforce only allowing removal of `messages` when `changes` is set and vice versa.

**Comment by mvantellingen** [comment]
I think this is already fixed in the latest release. We need to check

**Comment by tayzlor** [comment]
I'm experiencing a similar issue where i'm trying to change a subscription. The proposed terraform plan is 

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.commercetools.commercetools_subscription.cart_events_pubsub will be updated in-place
  ~ resource "commercetools_subscription" "cart_events_pubsub" {
        id      = "f8083722-9836-4fa4-b94d-263fbcb23380"
        # (2 unchanged attributes hidden)

      + changes {
          + resource_type_ids = [
              + "cart",
            ]
        }

      ~ destination {
          ~ topic      = "cart-events" -> "ct-cart-events"
            # (2 unchanged attributes hidden)
        }


      - message {
          - resource_type_id = "cart" -> null
          - types            = [] -> null
        }
        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

When executing this plan I get the following error message 

```
Request body does not contain valid JSON. actions -> messages: Missing required value
```

I'm using version 1.3.0-pre.0

**Comment by mvantellingen** [comment]
Should be fixed in main branch (next release)
