### ISSUE TITLE
LocalizedDescription missing in ShippingMethod resource

### ISSUE THREAD

**Issue by alfrescian** [labd/terraform-provider-commercetools#163]
current resource_shipping_method only covers deprecated description field and does not include new localizedDescription field.

```
resource "commercetools_shipping_method" "standard" {
  name            = "Standard Shipping"
  key             = "standard-shipping"
  localizedDescription = {
    en = "standard shipping"
    de = "Standard Versand"
  }
...
}
```

**Comment by qdegraaf** [comment]
Had a look at this. Although it should be a small/easy fix, the current [go-sdk](https://github.com/labd/commercetools-go-sdk) has the LocalizedDescription field, but types as a string. This leads to a marshalling issue. E.g.
```json
"localizedDescription": "{"en": "some description"}"
``` 
instead of 
```json
"localizedDescription": {"en": "some description"}
```

Which in turn leads to a 400. I want to avoid writing custom marshallers as that will get messy very fast. Both an update and a regen of the Go-sdk are on their way, one of those might fix the typing issue and then I'll finish this up.
