### ISSUE TITLE
commercetools_project_settings always updating the version - terraform enterprise

### ISSUE THREAD

**Issue by fabiostawinski** [labd/terraform-provider-commercetools#334]
**Information**
Terraform version:  1.3.2
Provider version: 1.6.0
Resource: commercetools_project_settings

**To Reproduce**
All runs, shows in the plan this
![image](https://user-images.githubusercontent.com/5034107/212310720-ffdcf88d-5edf-4587-ac46-df35a8643a0a.png)

```hcl

resource "commercetools_project_settings" "project_settings" {
  countries                  = var.config.countries
  currencies                 = var.config.currencies
  languages                  = var.config.languages
  name                       = upper(replace(var.config.project_key, "-", " "))
  enable_search_index_orders = var.config.enable_search_index_orders
}

```

I had tried to ignore it using 
```hcl

  lifecycle {
    ignore_changes = [
      version
    ]
  }

```

It stops showing in the plan, but then it breaks the apply
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/5034107/212311119-f762479a-8db2-4632-a67d-a2ba5f0134e8.png">

**Comment by pimvernooij** [comment]
Could you upgrade tot 1.6.2 and see if it is solved?

**Comment by mvantellingen** [comment]
Can you run with `CTP_DEBUG=1 TF_LOG=debug terraform apply` ? It should show you the JSON we generate and send to commercetools.

What seems to happen is that terraform thinks that there are no changes but we do an update anyway. I ran into a similar bug with another resource using the new terraform-plugin-framework

**Comment by Engerim** [comment]
I ran into the same issue, the problem is  `ShippingRateInputType` if you don't have it set, as you are using fixed, it will still run always in the path to set the input type with an empty action which updates the project always. 

Deep Dive if you did not have set the `ShippingRateInputType` it is the `ValueStateNull` and a equal call for both is always false as the equal function the framework is also looking into the `state` where both are the same but still are compared as false
