### ISSUE TITLE
No AwsAuthenticationMode available in case IAM authentication is used

### ISSUE THREAD

**Issue by jetrohd** [labd/terraform-provider-commercetools#352]
Hello, I would appreciate if you could support the new AWS IAM Authentication mode when using Terraform resource "commercetools_subscription". I get this error when no access key is specified, and I can't set the AWS IAM authentication:

 Error: required property 'access_key' is empty
│ 
│   with commercetools_subscription.vk-test-subscription,
│   on subscriptions.tf line 8, in resource "commercetools_subscription" "vk-test-subscription":
│    8: resource "commercetools_subscription" "vk-test-subscription" {

No AwsAuthenticationMode available: 

AwsAuthenticationMode: Defines the method of authentication for the SQS queue.

https://commercetools.github.io/commercetools-sdk-java-v2/javadoc/com/commercetools/api/models/subscription/SqsDestinationImpl.html

Thanks a lot in advance.

**Comment by JonesAtWerk** [comment]
Hello! I would like this feature as well. Looks like I'm unable to create a subscription unless i use credentials, but i do not want to do that. The CT api works just fine with my setup.

**Comment by demeyerthom** [comment]
Hi @jetrohd @JonesAtWerk 

We set the auth mode dynamically based on the presence of `access_key` (see https://github.com/labd/terraform-provider-commercetools/blob/da7be93d6123390cc223bb2dffedd674360b6b20/internal/resources/subscription/model.go#L279). If `access_key` is provided we set the mode to `Credentials`, if it is **not** provided we set it to `IAM` 

This has been implemented since the beginning of this year, so not seeing it working currently might have to do with an older version of this provider? Can you verify if your provider is [v1.6.0](https://github.com/labd/terraform-provider-commercetools/releases/tag/v1.6.0) or later? 

I am closing the ticket now as this feature is implemented, but come back to me if you are still encountering issues!
