### ISSUE TITLE
Upgrading 0.29.3 to 1.6.9 throws ans error in commercetools_subscription resource

### ISSUE THREAD

**Issue by abosenko** [labd/terraform-provider-commercetools#355]
**Information**
Terraform version: 1.1.7

Provider version: 0.29.3
Resource: commercetools_subscription

**To Reproduce**
Upgrade hashicorp/aws version from 3.49.0 to 4.58.0
Upgrade labd/commercetools version from 0.29.3 to 1.6.9

New code
```hcl
resource "commercetools_subscription" "cart_discounts_subscription" {
  key = "sns_cart_discounts_subscription"

  destination {
    type          = "SNS"
    topic_arn     = data.aws_ssm_parameter.cart_discounts_topic_arn.value
    access_key    = data.aws_ssm_parameter.user_key.value
    access_secret = data.aws_ssm_parameter.user_secret.value
    region        = var.aws_region
  }

  changes {
    resource_type_ids = ["cart-discount"]
  }

  format {
    type = "Platform"
  }
}
```

Old code:
```hcl
resource "commercetools_subscription" "cart_discounts_subscription" {
  key = "sns_cart_discounts_subscription"

  destination = {
    type          = "SNS"
    topic_arn     = data.aws_ssm_parameter.cart_discounts_topic_arn.value
    access_key    = data.aws_ssm_parameter.user_key.value
    access_secret = data.aws_ssm_parameter.user_secret.value
    region        = var.aws_region
  }

  changes {
    resource_type_ids = ["cart-discount"]
  }
}
```

Error message:
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.subscriptions.commercetools_subscription.cart_discounts_subscription,
│ provider "provider[\"registry.terraform.io/labd/commercetools\"]" produced
│ an unexpected new value: .destination[0].region: was
│ cty.StringVal("eu-central-1"), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by fabiostawinski** [comment]
Same happening here.

**Comment by demeyerthom** [comment]
Hi @abosenko! Thanks for reaching out!

This is not exactly a bug, but rather a badly documented migration path. the SNS topic type does not require `region` as a field, but it is still in the resource definition specified here. This will not throw an error when running plan etc, but **will** throw an error after apply, because it expects the aws_region to be there, but it never gets set on the state because it is not required. 

We could probably do with a bit better validation of inputs here up front, but removing region should fix your issue.

Assuming you have not fixed it on your own already after 5 months :)
