### ISSUE TITLE
Error: Discount codes without `max_applications` do not work

### ISSUE THREAD

**Issue by Rtwena** [labd/terraform-provider-commercetools#449]
When trying to setup a discount code that can be used infinitely, by either not supplying `max_applications` or setting `max_applications = 0`, then the code does not trigger any discounts.

Fetching the discount code from commercertools via HTTP /discount-codes endpoint shows
```
            "maxApplications": 0,
            "maxApplicationsPerCustomer": 0,
```
And in commercetools merchant centre, it shows nothing 
![image](https://github.com/labd/terraform-provider-commercetools/assets/10722219/5ad4ed02-25ab-4c36-b712-b1d2df66759d)

However, discounts are not being applied to the cart.

If I then change the number of "Max applications" to 0 in merchant centre. Then the discount code is working at intended.
And fetching the code via HTTP /discount-codes, now does not return `maxApplications`

My assumption is the plugin is forcing the value to be `0` rather than `null`, which commercetools doesn't like.

**Comment by demeyerthom** [comment]
@Rtwena yes, this looks like a bug due to an engine constraint on the current provider. It uses the default Go values for scalars when a field gets unset (so empty string or, in this case, 0). This means that we don't unset the value, but instead set it to 0.

I will create a fix to internally treat 0 as an unset instead. This will make the actual value for 0 ambiguous, so that will not be possible anymore until we move to a new version of the provider SDK
