### ISSUE TITLE
Import entity into the state automatically during plan/apply execution

### ISSUE THREAD

**Issue by roman-sokolovych-valtech** [labd/terraform-provider-commercetools#533]
I have an issue with the terraform apply command during the GitHub action execution if some entity was already manually created in the commercetools with the same "key".

![image](https://github.com/user-attachments/assets/4ac11e47-e5ab-4876-aefa-e152a98614d0)

Is it possible automatically import entity by key into the terraform state if is was already created in the commercetools manually?

**Comment by demeyerthom** [comment]
Hi @roman-sokolovych-valtech did you run an import for that same resource beforehand? Like `terraform import commercetools_product_type.test_type_creation`? This way terraform will take the existing type into state.

Commercetools does not allow multiple entities with the same key, so the error happens because terraform tries to create a new resource based on it missing in state, but encounters an error in CT because the key exists
